/*
 * DesignerFrame.java
 *
 * Created on 2007年9月8日, 下午3:05
 */

package dyno.swing.designer.main;

import java.awt.BorderLayout;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.Introspector;
import javax.swing.JButton;
import javax.swing.UIManager;

/**
 *
 * @author  rehte
 */
public class MainFrame extends javax.swing.JFrame {
    /** Creates new form DesignerFrame */
    public MainFrame() {
        initComponents();
        designer.newPanel();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("frame.png")));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        designer = new dyno.swing.designer.main.DesigningPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Swing Designer");
        getContentPane().add(designer, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        Introspector.setBeanInfoSearchPath(new String[]{"dyno.swing.designer.beaninfo"});
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainFrame frame = new MainFrame();
                frame.setSize(1146, 832);
                frame.setLocationRelativeTo(null);
                frame.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private dyno.swing.designer.main.DesigningPanel designer;
    // End of variables declaration//GEN-END:variables
}